name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  my-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [17]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}

      - name: install modules
        run: npm install

      - name: linting typescript
        run: npx lint-staged
        if: always()

      - name: linting css
        run: npm run lint:scss
        if: always()

      - name: unit testing
        run: npm run test:unit
        if: always()
