name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  my-pipeline:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        version: [18]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}

      - name: install modules
        run: npm ci

      - name: linting typescript
        run: npx lint-staged
        if: always()

      - name: linting css
        run: npm run lint:scss
        if: always()

      - name: unit testing
        run: npm run test:unit
        if: always()

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'reports'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
